### getAll
GET http://localhost:3001/api/persons

### delete
DELETE http://localhost:3001/api/persons/3

### create
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name":"Mary Poppendieck",
  "number":"hola"
}